server:
  port: 8080

management.endpoints.web.exposure.include: health,info
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.labs64: DEBUG
    org.springframework.cloud.stream: INFO

application:
  default-broker: rabbit

spring:
  application:
    name: labs64.io-api-gateway
  cloud:
    stream:
      bindings:
        rabbit-out-0:
          destination: labs64-audit-topic
          binder: rabbit
      rabbit:
        bindings:
          rabbit-out-0:
            producer:
              exchangeType: topic
  rabbitmq:
    host: rabbitmq.default.svc.cluster.local
    port: 5672
    username:
    password:
