server:
  port: 8080

management.endpoints.web.exposure.include: health,info
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.labs64: DEBUG

spring:
  application:
    name: labs64.io-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes: []
            #- id: auditflow_service_route
            #  uri: lb://labs64io-auditflow
            #  predicates:
            #    - Path=/api/v1/audit/**
            #- id: ecommerce_service_route
            #  uri: lb://labs64io-ecommerce
            #  predicates:
            #    - Path=/api/v1/cart/**
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    urls: []
      #- name: auditflow
      #  url: http://labs64io-auditflow.localhost/v3/api-docs
      #- name: ecommerce
      #  url: http://labs64io-ecommerce.localhost/v3/api-docs
